services:
  website:
    image: sthack-interface-2021
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:4400
    environment:
      NODE_ENV: production
      NODE_PATH: ./
      APP_MONGO: mongodb://sthack-admin:sthack-password@mongo:27017
      APP_MONGO_DB: sthack-scoreboard
      APP_REDIS: redis://redis:6379
      APP_SALT: thisismysalt
    networks:
      - apps
    depends_on:
      - mongo
      - redis

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sthack-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: sthack-password
      ME_CONFIG_MONGODB_URL: mongodb://sthack-admin:sthack-password@mongo:27017/
    networks:
      - apps
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sthack-admin
      MONGO_INITDB_ROOT_PASSWORD: sthack-password
      MONGO_INITDB_DATABASE: sthack-scoreboard
    volumes:
      # - ./2021:/docker-entrypoint-initdb.d/
      # - ./2022:/docker-entrypoint-initdb.d/
      # - ./2023:/docker-entrypoint-initdb.d/
      - ./_mongo_import.sh:/docker-entrypoint-initdb.d/_mongo_import.sh
      - mongo-data:/data/db
    networks:
      - apps

  redis:
    image: redis
    restart: always
    # ports:
    #   - 6379:6379
    networks:
      - apps

volumes:
  mongo-data:

networks:
  apps:
